// Dữ liệu 27 đòn sát chiêu thực dụng — viết lại bằng lời riêng (nguồn nội bộ chỉ để nắm ý, KHÔNG chép).
// key: slug đòn · nhom: nhóm quân chủ lực · dinh: định nghĩa · cong: khẩu quyết khi tấn công · thu: khẩu quyết khi phòng thủ
// tag: nhãn nhận diện tự động trong lời giải (analyse-sct.mjs) — null nếu không nhận diện chắc chắn được
// dt: bài ví dụ trong chuyên đề "Sát Pháp Đại Toàn" (cùng hình, có thể khác tên gọi) — null nếu không có
module.exports = [
  // ---------- Đòn Pháo ----------
  { key: 'giap-xe-phao', ten: 'Giáp Xe Pháo', nhom: 'Pháo', tag: 'giap-xe-phao', dt: 'giap-xe-phao-vi-du-1',
    dinh: 'Một Xe đứng kẹp giữa hai Pháo trên cùng một đường. Pháo trước, Xe giữa, Pháo sau tạo thành một khối chiếu liên tiếp: Xe rời đi là Pháo chiếu, Pháo chiếu xong Xe lại chiếu.',
    cong: ['Pháo sau là gốc rễ — giữ Pháo sau an toàn trước tiên', 'Dồn đòn vào ba hàng cuối của đối phương', 'Xe rời chỗ là chiếu rút: vừa chiếu vừa bắt quân', 'Đề phòng Tượng, Mã đối phương canh chân Pháo sau'],
    thu: ['Nhằm thẳng Pháo sau mà đuổi hoặc mời đổi', 'Chiếm trước lộ Xe định đánh, mời đổi Xe', 'Chặn sớm khi đối phương định đưa Pháo thứ hai về'] },
  { key: 'thien-dia-phao', ten: 'Thiên Địa Pháo', nhom: 'Pháo', tag: 'thien-dia-phao', dt: 'thien-dia-phao-vi-du-1',
    dinh: 'Một Pháo đóng ở trung lộ ("thiên"), một Pháo nằm ở hàng đáy đối phương ("địa"), cùng kìm Sĩ Tượng không cho cử động. Thường có thêm Xe hoặc mặt Tướng góp sức.',
    cong: ['Pháo trên giữ trung lộ, Pháo dưới giữ hàng đáy', 'Sĩ Tượng bị kìm thì quân thứ ba đánh vào', 'Mặt Tướng khóa thêm một lộ là thế sát thành', 'Coi chừng quân đối phương chen vào giữa ngòi'],
    thu: ['Đuổi một trong hai Pháo là thế tan', 'Chèn quân vào ngòi — nhưng nhìn kỹ kẻo Pháo nổ Tượng', 'Mở đường cho Tướng thoát trước khi lưới khép'] },
  { key: 'song-hien-tuu', ten: 'Song Hiến Tửu', aka: 'Liên hoàn Pháo', nhom: 'Pháo', tag: null, dt: null,
    dinh: 'Hai Pháo là quân chủ lực, phối hợp liên hoàn với nhau, thường có thêm Xe nhòm lộ Tượng. Đòn này hay xuất hiện ngay từ khai cuộc Pháo đầu.',
    cong: ['Giữ Pháo sau an toàn, không cho quân chen giữa hai Pháo', 'Ngòi nên là quân nhà hoặc quân đứng yên một chỗ', 'Thiếu một Pháo liên hoàn thì phải có quân phá Tượng', 'Đòn hay đi kèm thí quân — tính hụt là trả giá đắt'],
    thu: ['Thấy Pháo nhòm lộ Tượng là phải cảnh giác', 'Đuổi Pháo sau, rút quân đang làm ngòi, chen vào giữa', 'Bay Tượng né trước, để quân khác giữ cửa'] },
  { key: 'phao-trung', ten: 'Pháo Trùng', nhom: 'Pháo', tag: 'phao-trung', dt: 'phao-trung-vi-du-1',
    dinh: 'Hai Pháo đứng nối nhau trên cùng một hàng dọc hoặc ngang: Pháo trước làm ngòi cho Pháo sau chiếu. Lót quân vào giữa Pháo trước và Tướng không cứu được, vì quân lót lại thành ngòi cho chính Pháo trước.',
    cong: ['Pháo trước làm ngòi, Pháo sau là sát thủ', 'Hai Pháo đứng sát, không để quân nào chen ngang', 'Sĩ đối phương yếu thì mượn luôn làm ngòi', 'Thêm Xe, Tướng, Chốt khóa đường chạy là xong'],
    thu: ['Đuổi hoặc khóa Pháo sau ngay từ đầu', 'Chặn Pháo trước tiến sát, chặn quân chen ngang', 'Quân chen vào coi chừng bị chiếu rút hoặc bị khóa chết'] },
  { key: 'phao-lan', ten: 'Pháo Lăn', nhom: 'Pháo', tag: 'phao-lan', dt: 'phao-trien-dan-sa-vi-du-1',
    dinh: 'Pháo đứng trước, phía sau có quân chờ sẵn (thường là Xe). Pháo rời đi là quân sau chiếu, nên Pháo được "lăn" tự do: ăn quân, đổi chỗ, rút về thủ mà vẫn giữ nước chiếu.',
    cong: ['Pháo lăn đi, quân sau chiếu — đó là chiếu rút', 'Mỗi lần lăn phải có mục tiêu: ăn quân hay dọa sát', 'Lăn rút trục dọc được cả công lẫn thủ', 'Bảo vệ quân phía sau, mất nó là mất đòn'],
    thu: ['Diệt hoặc chặn quân đứng phía sau Pháo', 'Bay Sĩ Tượng phía đối diện để Pháo lăn vào chỗ trống', 'Thêm quân giữ lộ Sĩ, kéo Pháo nhà về đỡ'] },
  { key: 'muon-sat', ten: 'Muộn Sát', nhom: 'Pháo', tag: 'muon-sat', dt: 'muon-cung-sat-vi-du-1',
    dinh: 'Pháo là quân tấn công chủ lực, mượn chính quân của đối phương làm ngòi. Quân bị mượn thường là quân đang bị tắc, không nhúc nhích được.',
    cong: ['Tìm quân tắc của đối phương — đó là ngòi của ta', 'Thí quân để lôi quân đối phương vào chỗ tắc', 'Mượn Pháo đối phương làm ngòi thì coi chừng bị nổ ngược', 'Pháo rút về chiếu, nhìn phía sau kẻo bị phản chiếu'],
    thu: ['Khai thông quân bị tắc, đừng để quân tự cản nhau', 'Đuổi Pháo chủ lực, đừng tham ăn quân mồi rồi bị tắc', 'Tìm ngòi để chiếu ngược khi bị mượn quân'] },
  { key: 'thiet-mon-thuyen', ten: 'Thiết Môn Thuyên', aka: 'Then cửa sắt', nhom: 'Pháo', tag: 'thiet-mon-thuyen', dt: 'thiet-mon-thuyen-vi-du-1',
    dinh: 'Pháo đầu đóng chặt trung lộ như then cửa, các quân khác khống chế để Tướng đối phương không về được lộ giữa, rồi Xe hoặc Chốt lao xuống sát cục.',
    cong: ['Pháo đầu là then cửa — bảo vệ nó trước tiên', 'Xe, Chốt áp sát nhưng đừng để bị đuổi hay mời đổi', 'Thêm ngòi, thêm căn, dồn toàn lực vào một cửa', 'Có thể thí Xe hoặc thí Sĩ để dựng then cửa'],
    thu: ['Tìm cách đổi Pháo đầu để gỡ then cửa', 'Mở đường cho Tướng chạy, canh lộ Tướng đối phương', 'Huy động quân giữ điểm sát, đổi Xe, bắt Chốt'] },
  { key: 'song-tien', ten: 'Song Tiên', nhom: 'Pháo', tag: null, dt: null,
    dinh: 'Xe và hai Pháo đánh trên hai hàng song song, giống đòn song Xe lệch. Hình dáng gần với Giáp Xe Pháo nhưng vị trí Xe khác hẳn — đặt Xe sai chỗ là đòn không thành.',
    cong: ['Đưa hai Pháo về sát nhau trên cùng một hàng, thường là hàng giữa', 'Bảo vệ Pháo sau', 'Xe phải linh hoạt, không bị cản đường chiếu', 'Xe một cánh, hai Pháo một cánh cũng là song tiên'],
    thu: ['Đuổi hoặc mời đổi Pháo sau', 'Chặn Pháo trước di chuyển', 'Chặn trước các đường chiếu của Xe'] },
  // ---------- Đòn Pháo Mã ----------
  { key: 'ma-hau-phao', ten: 'Mã Hậu Pháo', nhom: 'Pháo Mã', tag: 'ma-hau-phao', dt: null,
    dinh: 'Pháo và Mã là quân chủ lực: Pháo đứng phía sau, lấy Mã làm ngòi để chiếu hết hoặc bắt quân.',
    cong: ['Mã đi trước khóa Tướng, Pháo theo sau làm sát thủ', 'Pháo Mã đừng giẫm chân nhau', 'Điểm đích của Mã không được có quân đối phương dòm ngó', 'Thêm quân khóa đường đi của Tướng, rồi tính chiếu rút'],
    thu: ['Chen ngang hoặc cản trước mặt Pháo Mã', 'Mã chỉ có tối đa hai chân chiếu — canh cả hai', 'Chặn quân tiếp viện: chỉ có Pháo Mã thì rất khó sát'] },
  { key: 'luong-chieu', ten: 'Lưỡng Chiếu', nhom: 'Pháo Mã', tag: 'luong-chieu', dt: null,
    dinh: 'Một nước đi làm hai quân cùng chiếu một lúc, thường là quân vừa đi chiếu và quân phía sau được mở đường cũng chiếu. Đối phương không thể vừa lót vừa ăn, chỉ còn cách chạy Tướng.',
    cong: ['Một nước hai đường chiếu — lót không được, ăn cũng không xong', 'Xếp quân trước – quân sau trên cùng một đường với Tướng', 'Quân đi đầu nhảy vào ô chiếu, quân sau tự mở chiếu', 'Tướng phải chạy thì khóa sẵn đường chạy'],
    thu: ['Đừng để hai quân đối phương xếp thẳng hàng với Tướng', 'Chạy Tướng khỏi đường thẳng hàng trước khi bị lưỡng chiếu', 'Giữ sẵn ô thoát cho Tướng'] },
  // ---------- Đòn Xe Pháo ----------
  { key: 'xuyen-tam-cuc', ten: 'Xuyên Tâm Cục', aka: 'Đại đao xuyên tâm', nhom: 'Xe Pháo', tag: 'dai-dao-xuyen-tam', dt: 'dai-dam-xuyen-tam-vi-du-1',
    dinh: 'Xe (hoặc Pháo, Mã, Chốt) đánh thẳng vào Sĩ giữa — "tâm" của cung đối phương — tạo sức tấn công ác liệt. Hay gặp nhất là hai Xe một Pháo, Xe lao vào ăn Sĩ giữa: gọi là Đại đao xuyên tâm.',
    cong: ['Xe ăn Sĩ giữa là thí quân — tính đủ đường rồi hãy chém', 'Nhìn trước quân đối phương có thể lui về giữ lộ Sĩ, Tượng đáy', 'Hai cách đánh: bình Xe chiếu ngang hoặc hai Xe chiếu dọc', 'Không phải lúc nào cũng dùng được cả hai cách — chọn đúng'],
    thu: ['Đuổi quân chủ lực của hình xuyên tâm, thường là Pháo', 'Giữ Sĩ giữa, có sẵn quân lui về trợ thủ', 'Chạy Tướng thoát trước khi bị xuyên tâm, nhớ có quân hộ giá'] },
  // ---------- Đòn Xe Mã ----------
  { key: 'trac-dien-ho', ten: 'Trắc Diện Hổ', nhom: 'Xe Mã', tag: 'trac-dien-ho', dt: 'cao-dieu-ma-vi-du-1',
    dinh: 'Mã đứng ở hoa Chốt lộ 3 hoặc lộ 7 phía đối phương, khóa Tướng đứng lệch một bên, rồi Xe vào sát cục. Chuyên đề Sát Pháp Đại Toàn gọi đây là Cao Điều Mã.',
    cong: ['Đưa Xe và Mã về cùng một cánh', 'Mã bị nhòm thì Xe chiếu dọc, Xe bị nhòm hàng đáy thì chiếu ngang', 'Xe giữ lộ 5, không cho Tướng bình ra giữa', 'Tướng còn ở giữa thì ngọa tào lôi ra trước'],
    thu: ['Đổi hoặc chặn con Mã nguy hiểm, canh chân chiếu', 'Đỡ hàng đáy trước tiên, đừng để Tướng lơ lửng', 'Chạy Tướng vào lộ 5 cho Mã lạc chân'] },
  { key: 'ma-ngoa-tao', ten: 'Mã Ngọa Tào', nhom: 'Xe Mã', tag: 'ngoa-tao', dt: 'ma-ngoa-tao-vi-du-1',
    dinh: 'Mã nằm sát góc cung đối phương ở lộ 3 hoặc lộ 7 (ngay trên hàng đáy), chiếu chéo vào Tướng và khóa không cho Tướng về lộ 5. Quân khác phối hợp chiếu sát ở lộ 4, 6 hoặc hàng đáy.',
    cong: ['Mã đáp đầu Tượng để nhảy vào ô ngọa tào', 'Mặt Tướng trợ công cho đòn này cực mạnh', 'Bị Xe đuổi thì lấy quân khác làm căn cho Mã', 'Coi chừng quân cản của đối phương vây bắt Mã'],
    thu: ['Dùng Sĩ Tượng hoặc quân mạnh cản đường Mã vào', 'Quân cản của ta đừng biến thành quân tắc', 'Không bỏ trống một cánh cho Xe Mã quấy phá'] },
  { key: 'quai-giac-ma', ten: 'Quải Giác Mã', nhom: 'Xe Mã', tag: 'quai-giac', dt: 'quai-giac-ma-vi-du-1',
    dinh: 'Mã đứng ở góc cung trên cao (lộ 4 hoặc 6, ngay trên chân Sĩ), chiếu xuống Tướng, rồi quân khác — thường là Xe chiếu ngang hàng đáy — kết thúc.',
    cong: ['Mã góc cung chiếu xuống, Xe chiếu ngang hàng đáy', 'Chân Mã dọa ngọa tào có thể chuyển sang quải giác', 'Để ý quân làm tắc lầu ba của đối phương', 'Khéo chuyển sang các đòn đã học'],
    thu: ['Treo Sĩ đỡ chân Mã chiếu lộ 4, 6', 'Canh cả hai đường: ngọa tào lẫn quải giác', 'Thêm quân giữ, không xem thường mặt Tướng'] },
  { key: 'ma-khau', ten: 'Mã Khẩu', nhom: 'Xe Mã', tag: null, dt: null,
    dinh: 'Mã đứng ở vị trí canh được hai đường đi của Tướng đối phương, sau đó quân khác — thường là Xe — vào sát cục.',
    cong: ['Mã canh hai đường, quân khác bịt nốt đường còn lại', 'Mặt Tướng, Chốt, Pháo sau Sĩ đều là quân bịt đường', 'Chọn đúng hướng đứng, Mã khẩu rất dễ bị đuổi', 'Xe mượn mặt Tướng quấy hai sườn, có thể thí quân phá Sĩ'],
    thu: ['Né Tướng khỏi tầm Mã khẩu', 'Canh trước chân Mã hoặc cản chân Mã', 'Cản được một chân chưa phải là yên — Sĩ là quân giữ quý nhất'] },
  { key: 'dai-giac-ma', ten: 'Đại Giác Mã', nhom: 'Xe Mã', tag: 'dai-giac-ma', dt: null,
    dinh: 'Mã đứng ở lộ 4 hoặc 6 ngay trên hàng đáy đối phương, tại chân Sĩ dưới. Vị trí hẻo lánh, ít ai đề phòng, nhưng canh được các ô ở nách cung.',
    cong: ['Vị trí hẻo lánh nên đối phương hay bỏ sót', 'Có thể chuyển ngay thành Mã khẩu', 'Mã vào đây thường khó lui — không sát được thì dễ mất Mã'],
    thu: ['Đừng coi thường những ô hẻo lánh', 'Chặn quân phối hợp: một mình Mã không làm nên chuyện', 'Giam Mã không cho đường lui, tìm cách đổi hoặc ăn'] },
  { key: 'ma-dien', ten: 'Mã Điền', nhom: 'Xe Mã', tag: null, dt: 'bat-giac-ma-vi-du-1',
    dinh: 'Mã ghim chặt Tướng đối phương không di chuyển được, rồi quân khác vào sát. Giống Mã khẩu nhưng lợi hại hơn vì Tướng bị khóa hẳn. Chuyên đề Sát Pháp Đại Toàn gọi hình này là Bát Giác Mã.',
    cong: ['Khai thông thêm chân cho Mã', 'Dùng quân khác ép Tướng đi, rồi Mã khóa lại', 'Tướng bị khóa chặt thì chỉ cần một quân vào sát'],
    thu: ['Phòng như Mã khẩu', 'Đuổi Mã hoặc chặn trước quân tiếp viện', 'Cản bớt chân Mã rồi chạy lệch Tướng cho Mã lạc chân'] },
  { key: 'liet-ma-xe', ten: 'Liệt Mã Xe', nhom: 'Xe Mã', tag: 'liet-ma-xe', dt: 'bat-hoang-ma-vi-du-1',
    dinh: 'Xe đang đứng cản chân Mã; Xe rời đi là Mã chiếu Tướng. Đây là kiểu chiếu rút cực mạnh vì Xe được đi tự do ngang dọc.',
    cong: ['Xe rút ra, Mã tự chiếu — Xe muốn đi đâu cũng được', 'Chọn ô cho Xe thật đắt: chiếu tiếp hoặc bắt quân', 'Rút không sát thì rút ăn quân', 'Thêm quân phối hợp để đòn rút thành sát'],
    thu: ['Mời đổi Xe trước khi hình Liệt Mã Xe thành', 'Canh trước ô Mã sẽ đáp', 'Chưa bị dọa sát thì giấu quân tránh bị rút ăn'] },
  // ---------- Đòn Song Mã ----------
  { key: 'song-ma-am-tuyen', ten: 'Song Mã Ẩm Tuyền', nhom: 'Song Mã', tag: 'song-ma-am-tuyen', dt: 'song-ma-am-tuyen-vi-du-1',
    dinh: 'Hai Mã tấn công sát cánh nhau: một Mã khống chế đường đi của Tướng, một Mã chiếu hết.',
    cong: ['Hai Mã đứng gần nhau, cùng một cánh', 'Mã ở ô ngọa tào rút ra linh hoạt: bắt Tượng, bắt quân hoặc sát', 'Không ngọa tào được thì quải giác', 'Mở mặt Tướng trợ công khi cần'],
    thu: ['Dùng Pháo mượn Sĩ làm ngòi đuổi ngang, tách hai Mã', 'Chặn đường Mã lao lên như phòng ngọa tào', 'Đổi bớt một Mã là đòn yếu hẳn'] },
  // ---------- Đòn Song Xe ----------
  { key: 'song-xe-nhi', ten: 'Song Xe Nhĩ', nhom: 'Song Xe', tag: null, dt: null,
    dinh: 'Hai Xe tập trung đánh vào "tai" Sĩ — lộ 4 hoặc lộ 6 sát cung đối phương.',
    cong: ['Phá liên kết cặp Sĩ trước', 'Một Xe ghim Tướng, Xe kia đánh vào tai Sĩ', 'Thêm mặt Tướng trợ công càng mạnh'],
    thu: ['Song Xe ở gần thì coi chừng Pháo Mã đối phương thí lấy Sĩ', 'Chống Sĩ ngược phía hai Xe, coi chừng Xe mượn Tướng khóa Sĩ', 'Thêm quân giữ Sĩ hoặc dùng hai Tượng che phía song Xe'] },
  { key: 'nhi-xe-lech', ten: 'Nhị Xe Lệch', aka: 'Song Xe lệch', nhom: 'Song Xe', tag: 'nhi-xe-lech', dt: 'song-xe-thac-vi-du-1',
    dinh: 'Hai Xe đứng lệch lộ nhau, thay nhau chiếu Tướng ở ba hàng cuối của đối phương. Chuyên đề Sát Pháp Đại Toàn có hình tương tự tên Song Xe Thác.',
    cong: ['Hai Xe lệch lộ để không giẫm chân nhau', 'Một Xe chiếu, Xe kia giữ hàng bên cạnh', 'Làm Tướng lơ lửng, không cho về chỗ an toàn', 'Đối phương có Pháo canh một hàng thì bịt hàng đó trước'],
    thu: ['Lót Xe trước mặt Tướng, dùng Pháo đỡ phía sau', 'Giữ Tướng ở chỗ có Sĩ Tượng che', 'Có song Xe đối phương thì tránh để Tướng lơ lửng'] },
  { key: 'trat-sat', ten: 'Trất Sát', nhom: 'Song Xe', tag: 'trat-sat', dt: null,
    dinh: 'Hai Xe phối hợp: thí một Xe để quân đối phương tự làm tắc đường Tướng, rồi Xe còn lại vào sát cục.',
    cong: ['Xác định rõ quân nào sẽ thành quân tắc', 'Điểm sát của Xe còn lại phải không có quân giữ', 'Đòn thí Xe: tính sai một nước là thua'],
    thu: ['Giữ sẵn quân đỡ đường sát của Xe còn lại', 'Đổi bớt một Xe mạnh của đối phương', 'Tương kế tựu kế cho đối phương thí Xe vô ích'] },
  { key: 'xe-lua-don-toa', ten: 'Xe Lửa Dồn Toa', nhom: 'Song Xe', tag: 'xe-lua-don-toa', dt: null,
    dinh: 'Hai Xe nối đuôi nhau trên cùng một đường như các toa tàu: Xe trước chiếu, Xe sau đỡ lưng và dồn tới. Sức phá Sĩ Tượng rất mạnh.',
    cong: ['Hai Xe nối đuôi trên một hàng ngang hoặc một lộ dọc', 'Chọn đúng: chiếu dọc hay chiếu ngang', 'Kéo Tướng ra chỗ xấu rồi dồn toa sát', 'Để ý quân tắc của đối phương để chiếu liên hoàn'],
    thu: ['Đưa quân mạnh về giữ, đảo Sĩ Tượng che Tướng', 'Canh đường ngang dọc của hai Xe, không cho xếp toa', 'Chỉ có hai Xe thì giữ kín Tướng là đủ — thêm Pháo Mã mới đáng lo'] },
  // ---------- Đòn Chốt ----------
  { key: 'tam-tien-tot', ten: 'Tam Tiến Tốt', nhom: 'Chốt', tag: 'tam-tien-tot', dt: null,
    dinh: 'Chốt tiến liên tục ba nước, ép Tướng đối phương vào đường cùng, rồi quân khác vào sát.',
    cong: ['Phá Sĩ trước để dọn đường cho Chốt', 'Chốt phải áp sát Tướng từng bước, không bị cản', 'Có quân làm căn thì Chốt mới vào sâu được'],
    thu: ['Đứng Tướng ở nơi an toàn, ngược phía với Chốt', 'Đưa quân chặn đường Chốt', 'Chốt có quân dìu thì dùng hai quân mạnh ăn Chốt'] },
  { key: 'tieu-dao-xuyen-tam', ten: 'Tiểu Đao Xuyên Tâm', nhom: 'Chốt', tag: 'tieu-dao-xuyen-tam', dt: null,
    dinh: 'Chốt đánh thẳng vào Sĩ giữa của đối phương, các quân khác phối hợp sát cục. Nhẹ hơn Đại đao xuyên tâm vì Chốt chỉ đi được từng bước.',
    cong: ['Chốt ăn Sĩ giữa mở toang trung cung', 'Chốt dễ chết uổng — tính kỹ để dùng hết sức nó', 'Một Chốt xuyên tâm có thể mở cả trận tấn công'],
    thu: ['Giữ lộ 4, 6 cho Tướng, chặn Xe chiếu ngang', 'Chốt chiếu dọc chưa sát ngay — còn kịp đỡ', 'Chặn quân phối hợp thì Chốt đơn độc vô hại'] },
  { key: 'nhat-tot-tong-chung', ten: 'Nhất Tốt Tống Chung', nhom: 'Chốt', tag: 'nhat-tot-tong-chung', dt: null,
    dinh: 'Chốt là quân chủ lực, chiếu liên tục và ép Tướng lùi dần đến khi hết đường thoát.',
    cong: ['Quân hỗ trợ tạo nước cho Chốt chiếu liên hoàn', 'Nhất là quân làm căn phía sau Chốt', 'Đường Chốt đi không được có quân cản', 'Kiểm lại: quân đối phương đã bị khóa hết chưa'],
    thu: ['Diệt quân hỗ trợ, phá căn phía sau Chốt', 'Khai thông quân đang bị tắc', 'Đưa quân chắn đường đi của Chốt'] },
  { key: 'tien-chot-hau-phao', ten: 'Tiền Chốt Hậu Pháo', nhom: 'Chốt', tag: 'tien-chot-hau-phao', dt: null,
    dinh: 'Chốt đứng trước, Pháo đứng sau trên cùng một đường, lấy Chốt làm ngòi chiếu Tướng — giống Mã hậu pháo nhưng ngòi là Chốt.',
    cong: ['Chốt đi trước khóa ô, Pháo theo sau chiếu', 'Chốt càng sát Tướng, Pháo càng khó đỡ', 'Thêm quân bịt đường chạy là thế sát'],
    thu: ['Ăn hoặc chặn Chốt trước khi nó áp sát', 'Chen quân vào giữa Chốt và Pháo', 'Giữ ô thoát cho Tướng ngoài đường Pháo'] },
];
