// Cờ tàn Chốt. id: [tên bài, kết quả ('thang'|'kheo'|'hoa'|'bt'), [khẩu quyết...], {ply: lời giảng}?, {biến: {i: lời}}?]
module.exports = {
  'ca-1': ['Một Chốt Hòa Một Sĩ', 'hoa', ['Bên giữ hòa chỉ cần Sĩ đi qua lại đúng nhịp, Tướng không rời cung.', 'Chốt đơn không có quân hỗ trợ thì không phá nổi Sĩ — đừng để Sĩ bị bắt chết vì đi sai ô.'], { 5: 'Đen có hai cách đỡ: Sĩ lui về lộ 4 hoặc lộ 6 đều giữ được.', 12: 'Hòa cờ.' }, { 0: { 1: 'Đây là nước sai của Đen.' } }],
  'ca-2': ['Một Chốt Và Tượng Khéo Thắng Một Sĩ', 'kheo', ['Chốt phải kẹp nách (đứng sát cạnh Sĩ, ép vào cửa cung).', 'Tướng Đỏ chiếm nốt mặt còn lại để Tướng Đen hết chỗ đứng.']],
  'ca-3': ['Một Chốt Khéo Hòa Pháo Sĩ', 'hoa', ['Chốt phải canh không cho Tướng Đen chiếm trung lộ.', 'Đỏ cảm tử đổi Chốt để bắt chết Sĩ Đen.', 'Coi chừng Pháo vòng ra sau bắt chết Chốt.']],
  'cb-1': ['Hai Chốt Thắng Hai Sĩ', 'thang', ['Một Chốt đứng ở chân Tượng giữa (hàng 5) làm chỗ dựa.', 'Chốt còn lại lo ép Tướng.', 'Tướng Đỏ trợ công, đổi một Chốt lấy cả hai Sĩ.']],
  'cb-10': ['Hai Chốt Khéo Thắng Chốt Sĩ', 'kheo', ['Hai Chốt dìu nhau, kẹp cung Tướng Đen.', 'Tướng Đỏ trợ công để Chốt khống chế Chốt Đen — Đen buộc phải dùng Chốt che mặt.', 'Dùng nước chiếu nhấp Tướng khiến Đen hết nước đi.', 'Khi cần thì dùng Chốt lụt (Chốt đã xuống đáy) một cách khéo léo.']],
  'cb-11': ['Hai Chốt Hòa Chốt Sĩ', 'hoa', ['Đen dùng Tướng chiếm một mặt.', 'Dùng Sĩ chặn không cho Chốt Đỏ tiến xuống.', 'Dùng Chốt của mình để che mặt Tướng.']],
  'cb-12': ['Hai Chốt Khéo Thắng Khuyết Sĩ', 'kheo', ['Chốt lộ 6 khống chế toàn cục.', 'Chốt lộ 5 chỉ cần di chuyển chiếm nốt mặt còn lại.', 'Tướng trợ công kết thúc.']],
  'cb-13': ['Hai Chốt Khéo Thắng Khuyết Tượng', 'kheo', ['Tướng Đỏ đứng trung lộ khống chế toàn cục.', 'Cứ đưa Chốt xuống đáy sát cục — Đen hết nước đi.']],
  'cb-14': ['Hai Chốt Thắng Mã', 'thang', ['Dùng Tướng khóa Mã — đòn rất hay dùng trong tàn cuộc có Mã.', 'Hai Chốt kẹp Tướng, ép dần.', 'Đừng quên Tướng trợ công cho hai Chốt, khiến Mã phải lo phòng thủ.']],
  'cb-15': ['Hai Chốt Thắng Pháo', 'thang', ['Đưa hai Chốt sát cung Tướng, phối hợp lộ mặt Tướng để một Chốt chiếm trung lộ là thắng dễ.', 'Không vội đẩy cả hai Chốt xuống sâu.', 'Coi chừng Pháo luồn ra sau Tướng bắt chết Chốt.']],
  'cb-2': ['Hai Chốt Thắng Hai Tượng', 'thang', ['Hai Chốt luôn đứng cao hơn hoặc ngang Tướng Đen, không thấp hơn.', 'Một Chốt không vội xuống thấp để còn phối hợp với Tướng sát cục.', 'Tướng Đỏ trợ công cho Chốt tiến xuống.']],
  'cb-3': ['Hai Chốt Thấp Thắng Hai Tượng', 'thang', ['Nhìn ra điểm yếu: Tượng đứng ngược bên (nếu Tượng ở lộ 3 thì thành hòa).', 'Tướng Đỏ lập tức chiếm trung lộ khóa Tượng giữa.', 'Chốt lộ 3 bắt chết Tượng lộ 7 — Đen hết nước đi.']],
  'cb-4': ['Hai Chốt Thấp Khéo Thắng Hai Tượng', 'kheo', ['Tướng khống chế Tượng giữa, chớp thời cơ chiếm lộ 4.', 'Hai Chốt tập trung tấn công ở lộ 6.']],
  'cb-5': ['Hai Chốt Khéo Thắng Hai Sĩ', 'kheo', ['Tướng trợ công cho Chốt chiếm trục lộ 6, lệch xuống dần.', 'Hai Chốt ép Tướng Đen sang lộ 6.', 'Khi Đen hết nước đi thì dùng nước nhấp ăn Sĩ.']],
  'cb-6': ['Hai Chốt Thấp Hòa Hai Sĩ', 'hoa', ['Đen luôn giữ Tướng ở tầng 2 hoặc tầng 3.', 'Dùng Sĩ để có nước đi (tránh hết nước).', 'Bỏ Sĩ dưới cho Chốt lụt — vẫn hòa.']],
  'cb-7': ['Hai Chốt Hòa Sĩ Tượng Lẻ', 'hoa', ['Tướng Đen phải nhanh chóng chiếm một mặt.', 'Dùng Sĩ giữ Chốt lộ 6 của Đỏ.', 'Khi Tướng Đỏ đứng lộ 5, coi chừng nước bỏ Chốt vào Sĩ để lộ mặt Tướng.']],
  'cb-8': ['Hai Chốt Thấp Khéo Thắng Sĩ Tượng Lẻ', 'kheo', ['Chốt lộ 5 uy hiếp thẳng Sĩ và Tượng ở hàng trên.', 'Chốt lộ 4 khống chế Sĩ Tượng, không cho Sĩ lui về lộ 5.', 'Tướng khéo chiếm mặt lộ 6 hoặc trung lộ — Sĩ Đen ở đâu thì Tướng Đỏ theo đó.']],
  'cb-9': ['Hai Chốt Khéo Thắng Chốt Tượng', 'kheo', ['Hai Chốt kẹp hai mặt tiến xuống, khiến Tướng Đen không nhúc nhích được.', 'Dùng mặt Tướng trợ công, ép Chốt Đen phải đi che mặt.', 'Dùng nước nhấp để Tướng Đen hết nước đi.']],
  'cc-1': ['Ba Chốt Cao Thắng Sĩ Tượng Toàn', 'thang', ['Chốt phía bên kia Sĩ tiến xuống kẹp nách.', 'Hai Chốt còn lại phối hợp Tướng tiến xuống ở lộ 4.', 'Khi tiến xuống có thể hy sinh một Chốt lấy một Sĩ.']],
  'cc-10': ['Ba Chốt Thấp Hòa Sĩ Tượng Toàn', 'hoa', ['Tướng Đen chỉ cần giữ mặt ở lộ 4.', 'Giữ nguyên đội hình Sĩ liên kết chắc chắn, Đỏ không tiến Chốt xuống được.']],
  'cc-2': ['Ba Chốt Hòa Chốt Khuyết Tượng', 'hoa', ['Đen chỉ cần dùng Chốt che mặt Tướng Đỏ là giữ hòa dễ dàng.']],
  'cc-3': ['Ba Chốt Hòa Pháo Hai Sĩ', 'hoa', ['Tướng Đen giữ nguyên vị trí, không cho Đỏ đưa Chốt kẹp nách.', 'Pháo Đen đứng ngang hàng hai Chốt thấp của Đỏ để giữ.', 'Mượn Chốt Đỏ làm ngòi để Pháo bắt, quấy nhiều nước.'], {}, { 0: { 1: 'Nước sai — Sĩ bị bắt chết.' }, 3: { 1: 'Nước sai.' } }],
  'cc-4': ['Ba Chốt Hòa Pháo Sĩ Tượng Lẻ', 'hoa', ['Mượn Chốt Đỏ làm ngòi cho Pháo bắt Chốt.', 'Bỏ Pháo lấy Chốt để về tàn cuộc hai Chốt hòa Sĩ Tượng lẻ.', 'Phối hợp thêm Tướng bắt Chốt đã xuống sâu.']],
  'cc-5': ['Ba Chốt Khéo Thắng Pháo Hai Sĩ', 'kheo', ['Đổi một Chốt lấy hai Sĩ.', 'Khai thác Sĩ đang treo ở lộ 4.', 'Dùng Chốt lộ 3 ép dần Tướng Đen — Đen hết quân để đi.']],
  'cc-6': ['Ba Chốt Thấp Khéo Thắng Mã Hai Sĩ', 'kheo', ['Khai thác Tướng Đen đang đứng chỗ xấu.', 'Ba Chốt tập trung đánh vào Sĩ giữa hoặc lộ 4.', 'Tướng Đỏ đứng yên trung lộ khống chế cả Mã lẫn hai Sĩ — cực kỳ lợi hại.']],
  'cc-7': ['Ba Chốt Thấp Khéo Thắng Mã Hai Tượng', 'kheo', ['Điểm then chốt: dọa đưa Chốt vào cung.', 'Khéo bỏ Chốt lụt để kéo Tướng Đen vào chỗ xấu.', 'Hai Chốt kẹp nách phối hợp Tướng sát cục.'], {}, { 0: { 1: 'Nước sai.' } }],
  'cc-8': ['Ba Chốt Thấp Khéo Thắng Mã Hai Sĩ (Thế 2)', 'kheo', ['Đổi một Chốt lấy hai Sĩ.', 'Tướng đứng trung lộ uy hiếp, dồn công vào Sĩ giữa — Mã bị khống chế.', 'Dùng Chốt lộ 3 ép dần Tướng Đen đến hết nước đi.']],
  'cc-9': ['Ba Chốt Thắng Pháo Song Tượng', 'thang', ['Hai Chốt bên trái dìu nhau, hỗ trợ nhau.', 'Chốt bên phải phối hợp Tướng trợ công ép dần Tướng Đen.', 'Nếu Tướng Đen leo lên tầng 3 thì Tướng Đỏ chiếm trung lộ khóa chết, rồi dùng Chốt trên sát cục.']],
  'cd-bt': ['Bài Tập Tổng Hợp Tàn Cuộc Chốt', 'bt', ['Tìm cách đưa về các bài đã học: hai Chốt khéo thắng khuyết Tượng, khuyết Sĩ.', 'Dùng đòn “ba Chốt hàng dọc” dọa sát để đưa về thế khuyết Tượng hoặc khóa chết Tướng.', 'Tướng khống chế trung lộ, kết hợp Chốt bình biên và các nước nhấp cao khiến Đen mất liên kết.']],
  'cd-vd': ['Bài Tập: Sức Mạnh Của Chốt Lụt', 'bt', ['Chốt lụt (Chốt đã xuống đáy, ở đây là Chốt lộ 7) dùng rất nhiều và cực kỳ mạnh — đừng coi thường.']],
  'cd-vd2': ['Bài Tập: Hai Chốt Khéo Thắng Khuyết Sĩ', 'bt', ['Đây là dạng hai Chốt khéo thắng khuyết Sĩ đã học — hãy nhận ra hình và áp dụng khẩu quyết.']],
};
