<?php

// Từ điển chuẩn hoá tiêu đề bài học: nguồn .xqf đặt tên VIẾT HOA KHÔNG DẤU + viết tắt.
// Dùng bởi command cotuong:clean-titles. Chỉ map các cụm CHẮC CHẮN đúng — cụm không chắc để
// nguyên (thà không dấu còn hơn sai nghĩa).

return [

    // Viết tắt → cụm đầy đủ (áp dụng TRƯỚC, khớp cả hoa/thường, ranh giới từ).
    'abbreviations' => [
        'BCDT' => 'Bố Cục Định Thức',
        'DTBC' => 'Định Thức Bố Cục',
        'BPM'  => 'Bình Phong Mã',
        'BPDX' => 'Bàn Đầu Xe',
        'QHX'  => 'Quá Hà Xe',
        'CRX'  => 'Chậm Ra Xe',
        'TNCL' => 'Tiên Nhân Chỉ Lộ',
        'TNCT' => 'Tiên Nhân Chỉ Lộ',
        'DTBc' => 'Định Thức Bố Cục',
    ],

    // Cụm/từ không dấu → có dấu chuẩn. Khớp longest-first, không phân biệt hoa thường.
    // Cụm nhiều từ đặt trước để ưu tiên.
    'phrases' => [
        'tien nhan chi lo'   => 'Tiên Nhân Chỉ Lộ',
        'binh phong ma'      => 'Bình Phong Mã',
        'ban dau ma'         => 'Bàn Đầu Mã',
        'ngu cuu phao'       => 'Ngũ Cửu Pháo',
        'ngu that phao'      => 'Ngũ Thất Pháo',
        'quy boi phao'       => 'Quy Bối Pháo',
        'qua cung phao'      => 'Quá Cung Pháo',
        'uyen uong phao'     => 'Uyên Ương Pháo',
        'lanh mon phao'      => 'Lãnh Môn Pháo',
        'kim cau phao'       => 'Kim Câu Pháo',
        'si giac phao'       => 'Sĩ Giác Pháo',
        'tuan ha phao'       => 'Tuần Hà Pháo',
        'qua ha phao'        => 'Quá Hà Pháo',
        'de phao'            => 'Đề Pháo',
        'trung phao'         => 'Trung Pháo',
        'phao dau'           => 'Pháo Đầu',
        'song phao'          => 'Song Pháo',
        'phi tuong cuoc'     => 'Phi Tượng Cuộc',
        'phi tuong'          => 'Phi Tượng',
        'khoi ma cuoc'       => 'Khởi Mã Cuộc',
        'phe ma cuoc'        => 'Phế Mã Cuộc',
        'doi binh cuoc'      => 'Đối Binh Cuộc',
        'doi binh'           => 'Đối Binh',
        'giang ho cuoc'      => 'Giang Hồ Cuộc',
        'qua ha xe'          => 'Quá Hà Xe',
        'cham ra xe'         => 'Chậm Ra Xe',
        'hoanh xe'           => 'Hoành Xe',
        'truc xe'            => 'Trực Xe',
        'xuat dong'          => 'Xuất Động',
        'xuat xe'            => 'Xuất Xe',
        'song xe'            => 'Song Xe',
        'chiem suon'         => 'Chiếm Sườn',
        'uy luc'             => 'Uy Lực',
        'bo cuc dinh thuc'   => 'Bố Cục Định Thức',
        'dinh thuc'          => 'Định Thức',
        'bo cuc'             => 'Bố Cục',
        'khai cuoc'          => 'Khai Cuộc',
        'trung cuoc'         => 'Trung Cuộc',
        'tan cuoc'           => 'Tàn Cuộc',
        'tan thu'            => 'Tàn Thủ',
        'sat chieu'          => 'Sát Chiêu',
        'nguyen tac'         => 'Nguyên Tắc',
        'nguyen ly'          => 'Nguyên Lý',
        'bai giang'          => 'Bài Giảng',
        'trong diem'         => 'Trọng Điểm',
        'bai hoc'            => 'Bài Học',
        'linh hoat'          => 'Linh Hoạt',
        'thuc chien'         => 'Thực Chiến',
        'cach hoc'           => 'Cách Học',
        'tot nhat'           => 'Tốt Nhất',
        'cap tan'            => 'Cấp Tấn',
        'trung binh'         => 'Trung Binh',
        'thuan phao'         => 'Thuận Pháo',
        'nghich phao'        => 'Nghịch Pháo',
        'phi huu tuong'      => 'Phi Hữu Tượng',
        'huu si giac phao'   => 'Hữu Sĩ Giác Pháo',
        'chuyen tot'         => 'Chuyển Tốt',
        'doi tot'            => 'Đối Tốt',
        'thuc tot'           => 'Thực Tốt',
        'loai hinh'          => 'Loại Hình',
        'bien hoa'           => 'Biến Hoá',
        'huu tuong'          => 'Hữu Tượng',
        'that lo ma'         => 'Thất Lộ Mã',
        'thu nhat'           => 'Thứ Nhất',
        'thu hai'            => 'Thứ Hai',
        'thu ba'             => 'Thứ Ba',
        'cuoc thu'           => 'Cuộc Thứ',
        'dinh thu'           => 'Định Thức',
        'tot'                => 'Tốt',
        // từ đơn phổ biến
        'phao'  => 'Pháo',
        'chot'  => 'Chốt',
        'tuong' => 'Tướng',
        'doi'   => 'đối',
        'va'    => 'và',
        'cuoc'  => 'Cuộc',
    ],
];
